;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line
        fixup-whitespace
        forward-whitespace
        indent-for-tab-command
        my-backward-delete-word
        my-backward-seq
        my-forward-seq
        right-parentheses-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        my-mc/backward-char
        my-mc/backward-char
        my-mc/backward-char
        my-mc/backward-char
        my-mc/forward-char
        my-mc/forward-char
        my-mc/forward-char
        my-mc/forward-char
        my-mc/next-line
        my-mc/next-line
        my-mc/next-line
        my-mc/next-line
        my-mc/previous-line
        my-mc/previous-line
        my-mc/previous-line
        my-mc/previous-line
        ))
