;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-metaright
        ))

(setq mc/cmds-to-run-once
      '(
        mc/backward-char
        mc/forward-char
        mc/next-line
        mc/previous-line
        ))
